title: Nahom Yirga
email: nkyirga@bu.edu
description: 
  Methods for strongly correlated electrons. 
baseurl: "" 
github_username:  nkyirga

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - about.md

plugins:
  - jekyll-feed	
