title: Nahom Yirga
email: nkyirga@bu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Nahom's page. I am a research fellow at Boston University working with David Campbell on strongly correlated electron systems. Much of this site is devoted to the various methods I looked at over the course of my Phd. 
baseurl: "" 
github_username:  nkyirga

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - about.md

plugins:
  - jekyll-feed	
